erDiagram
    fct__viewings {
        string viewing_sk PK
        string user_fk FK
        string content_fk FK
        date date_fk FK
        string device_fk FK
        float view_duration_minutes
        float completion_rate
        boolean is_completed_view
    }

    dim__users {
        string user_sk PK
        int user_id
        int country
        string age
        float days_since_registration
    }

    dim__users ||--o{ fct__viewings : "user_fk"
    dim__content {
        string content_sk PK
        int content_id
        string title
        string series_name
        int season_number
        int episode_number
        string genre
        string target_age_group
        string production_type
        date release_date
        int release_year
        float duration_minutes
        float production_cost_euros
    }

    dim__content ||--o{ fct__viewings : "content_fk"
    dim__devices {
        string device_sk PK
        string device_type
        string os
    }

    dim__devices ||--o{ fct__viewings : "device_fk"
    dim__date {
        date date_sk PK
        date full_date
        int year
        string quarter
        string month
        int week_number
        string day_of_week
        boolean is_weekend
    }

    dim__date ||--o{ fct__viewings : "date_fk"
