#!/usr/bin/env -S uv run --script
# requires-python = ">=3.11"
# dependencies = [
#   "prefect",
#   "prefect-gcp",
#   "prefect-dbt",
#   "pyyaml",
#   "rich",
# ]
# ///

import argparse
import json
import os
import sys
from pathlib import Path
from typing import Dict, Any, List, Optional

import yaml
from rich.console import Console
from rich.panel import Panel
from rich.table import Table
try:
    from prefect_gcp.credentials import GcpCredentials
    from prefect_dbt.cli import BigQueryTargetConfigs, DbtCliProfile
except Exception:
    # Import errors will be handled at runtime if --save is used
    GcpCredentials = None
    BigQueryTargetConfigs = None
    DbtCliProfile = None

console = Console()


def load_terraform_outputs(path: Optional[Path]) -> Dict[str, Any]:
    if not path or not path.exists():
        if path:
            console.print(f"[yellow]Warning:[/yellow] Terraform outputs file not found at [bold]{path}[/bold]")
        return {}
    try:
        with open(path, "r") as f:
            payload = json.load(f)
            # Flatten outputs: allow both object-with-value and primitive style
            outputs = {k: (v.get("value") if isinstance(v, dict) and "value" in v else v) for k, v in payload.items()}
            return outputs
    except json.JSONDecodeError as exc:
        console.print(f"[red]Error:[/red] Failed to parse terraform outputs: {exc}")
        return {}


def parse_rendered_profiles(profile_path: Path) -> Dict[str, Any]:
    """Parse a rendered dbt profiles.yml (or template) and return target names and structure.

    Returns a mapping: {profile_name: {"targets": {...}, "default_target": str}}
    """
    if not profile_path.exists():
        raise FileNotFoundError(f"Profile file not found: {profile_path}")
    text = profile_path.read_text(encoding="utf-8")
    try:
        data = yaml.safe_load(text)
    except yaml.YAMLError as exc:
        raise RuntimeError(f"Failed to parse YAML template: {exc}")
    if not data or not isinstance(data, dict):
        raise RuntimeError("Template is not a YAML dict")
    profile_name = list(data.keys())[0]
    profile_cfg = data[profile_name]
    if "outputs" not in profile_cfg:
        raise RuntimeError("Template must contain an 'outputs' section")
    targets = profile_cfg["outputs"]
    default = profile_cfg.get("target", list(targets.keys())[0])
    return {"profile_name": profile_name, "targets": targets, "default_target": default}


def resolve_target_context(target_name: str, cfg: Dict[str, Any]) -> Dict[str, Any]:
    """Resolve a target's context using environment variables and TF outputs.

    - Prefer environment variables (env.<UPPER>), then TF outputs under both raw and normalized keys.
    """
    def norm(k: str) -> str:
        k = k.lower()
        for prefix in ("bq_", "project_", "gcp_", "google_"):
            if k.startswith(prefix):
                k = k[len(prefix):]
        for suffix in ("_id", "_name", "_path"):
            if k.endswith(suffix):
                k = k[: -len(suffix)]
        return k

    resolved = {}
    # Fields of interest
    for field in ("project", "dataset", "keyfile", "threads", "location"):
        env_k = f"{field.upper()}" if field != "keyfile" else "GCP_SA_KEY_PATH"
        value = os.environ.get(env_k)
        if value is None:
            # try direct field in the rendered profile (should be literal values)
            raw_val = cfg.get(field)
            if raw_val is not None:
                value = raw_val
        # no TF fallback: we rely on the rendered profile or env
        if value is None:
            value = None
        resolved[field] = value
    return resolved


def build_context_for_all_targets(parsed: Dict[str, Any], limit_targets: Optional[List[str]] = None) -> Dict[str, Dict[str, Any]]:
    targets_cfg = parsed["targets"]
    contexts = {}
    for target_name, cfg in targets_cfg.items():
        if limit_targets and target_name not in limit_targets:
            continue
        contexts[target_name] = resolve_target_context(target_name, cfg)
    return contexts


def cli() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Setup Prefect blocks for dbt profiles (simple CLI, dry-run supported)")
    parser.add_argument("--service-account", "-sa", type=Path, help="Path to service account JSON for GCP (optional)")
    parser.add_argument("--profiles", "-p", type=Path, default=Path("dbt/profiles.yml"), help="Path to rendered dbt profiles.yml (generated by mise)")
    parser.add_argument("--dry-run", action="store_true", help="Don't save any blocks; just print what would be created")
    parser.add_argument("--save", action="store_true", help="Actually save Prefect blocks (must be used carefully)")
    parser.add_argument("--overwrite", action="store_true", help="Overwrite existing blocks when saving")
    parser.add_argument("--no-verify", action="store_true", help="Skip loading created blocks to verify their fields")
    parser.add_argument("--targets", "-g", nargs="*", help="Limit which targets to configure (e.g., dev prod)")
    parser.add_argument("--credentials-block", "-c", default="gcp-credentials", help="Name to use for GCP credentials block")
    parser.add_argument("--prefix", "-x", default="dbt", help="Prefix for block names")
    return parser.parse_args()


def main():
    args = cli()
    if args.service_account and not args.service_account.exists():
        console.print(f"[red]Error:[/red] Service account not found at [bold]{args.service_account}[/bold]")
        sys.exit(1)
    # Parse rendered profiles.yml
    try:
        parsed = parse_rendered_profiles(args.profiles)
    except Exception as exc:
        console.print(f"[red]Error parsing template:[/red] {exc}")
        sys.exit(1)

    contexts = build_context_for_all_targets(parsed, limit_targets=args.targets)

    # Print what will be created
    table = Table(title="Prefect Block Plan")
    table.add_column("target")
    table.add_column("project")
    table.add_column("dataset")
    table.add_column("keyfile")
    table.add_column("location")
    for t, ctx in contexts.items():
        table.add_row(t, str(ctx.get("project") or ""), str(ctx.get("dataset") or ""), str(ctx.get("keyfile") or ""), str(ctx.get("location") or ""))
    console.print(table)

    do_save = args.save and not args.dry_run
    if args.dry_run:
        console.print(Panel("[yellow]Dry-run mode: no Prefect blocks will be saved.[/yellow]", title="Dry-run"))
        return

    # If we actually save, ensure Prefect classes are available
    if do_save:
        if GcpCredentials is None:
            console.print("[red]Error:[/red] prefect_gcp or prefect_dbt is not installed; cannot save blocks. Install required packages or run in dry-run mode.")
            sys.exit(1)
        # Iteratively create blocks for each target
        created = []
        for t, ctx in contexts.items():
            project = ctx.get("project")
            dataset = ctx.get("dataset")
            keyfile = ctx.get("keyfile")
            location = ctx.get("location")
            # Build block names
            credentials_block_name = f"{args.credentials_block}-{t}"
            target_block_name = f"{args.prefix}-bq-target-{t}"
            profile_block_name = f"{args.prefix}-cli-profile-{t}"

            # Create credentials
            try:
                sa_text = None
                if args.service_account:
                    sa_text = args.service_account.read_text(encoding="utf-8")
                elif keyfile:
                    keypath = Path(keyfile)
                    if not keypath.exists():
                        console.print(f"[red]Error:[/red] service account file for target '{t}' not found at {keyfile}")
                        continue
                    sa_text = keypath.read_text(encoding="utf-8")
                else:
                    console.print(f"[yellow]Warning:[/yellow] No service-account supplied for target '{t}'; skipping credentials creation")
                    sa_text = None

                credentials = None
                if sa_text:
                    credentials = GcpCredentials(project=project, service_account_info=sa_text)
                    credentials.save(credentials_block_name, overwrite=args.overwrite)
                    console.print(f"[green]Saved GcpCredentials:[/green] {credentials_block_name}")

                # Verify credentials by loading back
                if not args.no_verify and credentials is not None:
                    try:
                        loaded_creds = GcpCredentials.load(credentials_block_name)
                        # Do not print full service account; just print project and presence
                        console.print(f"[cyan]Verified GcpCredentials:[/cyan] {credentials_block_name} (project={loaded_creds.project})")
                    except Exception as exc:
                        console.print(f"[red]Error verifying credentials {credentials_block_name}:[/red] {exc}")

                # Create BigQuery target config
                if BigQueryTargetConfigs is not None and credentials is not None:
                    target_cfg = BigQueryTargetConfigs(
                        schema=dataset,
                        credentials=credentials,
                        project=project,
                        threads=int(ctx.get("threads") or 1),
                        extras={"location": location, "method": "service-account-json"},
                    )
                    target_cfg.save(target_block_name, overwrite=args.overwrite)
                    console.print(f"[green]Saved BigQueryTargetConfigs:[/green] {target_block_name}")

                    # Verify target config
                    if not args.no_verify:
                        try:
                            loaded_target = BigQueryTargetConfigs.load(target_block_name)
                            console.print(f"[cyan]Verified BigQueryTargetConfigs:[/cyan] {target_block_name} (schema={loaded_target.schema}, project={loaded_target.project}, threads={getattr(loaded_target, 'threads', 'n/a')})")
                        except Exception as exc:
                            console.print(f"[red]Error verifying target config {target_block_name}:[/red] {exc}")

                # Create dbt profile block
                if DbtCliProfile is not None and BigQueryTargetConfigs is not None:
                    # we use the object we created (target_cfg) as target_configs
                    dbt_profile = DbtCliProfile(name=parsed["profile_name"], target=t, target_configs=target_cfg)
                    dbt_profile.save(profile_block_name, overwrite=args.overwrite)
                    console.print(f"[green]Saved DbtCliProfile:[/green] {profile_block_name}")

                    # Verify dbt profile
                    if not args.no_verify:
                        try:
                            loaded_profile = DbtCliProfile.load(profile_block_name)
                            console.print(f"[cyan]Verified DbtCliProfile:[/cyan] {profile_block_name} (name={loaded_profile.name}, target={loaded_profile.target})")
                        except Exception as exc:
                            console.print(f"[red]Error verifying DBT profile {profile_block_name}:[/red] {exc}")

                created.append({
                    "target": t,
                    "credentials_block_name": credentials_block_name,
                    "target_block_name": target_block_name,
                    "profile_block_name": profile_block_name,
                    "verified": True,
                })
            except Exception as exc:
                console.print(f"[red]Error creating blocks for target {t}:[/red] {exc}")

        # Summarize created blocks
        summary = Table(title="Block Creation Summary")
        summary.add_column("target")
        summary.add_column("credentials")
        summary.add_column("target_cfg")
        summary.add_column("dbt_profile")
        for item in created:
            summary.add_row(
                item.get("target"),
                item.get("credentials_block_name"),
                item.get("target_block_name"),
                item.get("profile_block_name"),
            )
        console.print(summary)
        console.print(Panel(f"Successfully created blocks: {len(created)}", title="Done", border_style="green"))
    else:
        console.print(Panel("[yellow]Dry-run mode: no blocks were created. Use --save to create blocks.", title="Dry-run"))


if __name__ == "__main__":
    main()