#import "@preview/typslides:1.3.0": *

// Project configuration
#show: typslides.with(
  ratio: "16-9",
  theme: "bluey",
  // font: "Roboto", // Using default font
  font-size: 20pt,
  link-style: "color",
  show-progress: true,
)

// --- Section 1: Context & Data Scope (0:00 - 3:00) ---

// Slide 1: Cover Slide
#front-slide(
  title: "Data Treatment Platform",
  subtitle: "ELT Pipeline Architecture",
  authors: "Nath, Cyp, Paul, Speaker 1, Speaker 2",
  info: [November 30, 2025],
)

// Slide 2: Introduction & Subject Recap
#slide(title: "Introduction & Subject Recap")[
  #cols(columns: (1fr, 1fr), gutter: 1em)[
    *Context & Goals*
    - *Project Goal:* Build a scalable Data Platform for BigMedia.
    - *Problem:* Need to process large volumes of viewing logs and user data.
    - *Objective:* Enable data-driven decision making via PowerBI dashboards.
  ][
    // Placeholder for a context image or icon
    #align(center + horizon)[
      #rect(width: 80%, height: 60%, fill: luma(240), radius: 10pt)[
        #align(center + horizon)[*Business Context Image*]
      ]
    ]
  ]
  
  #v(1em)
  *Why this platform?*
  - Centralize data from multiple sources.
  - Ensure data quality and consistency.
  - Provide near real-time insights.
]

// Slide 3: Source Data (Semantics)
#slide(title: "Source Data (Semantics)")[
  *Data Sources Generated by Faker*
  
  #table(
    columns: (1fr, 2fr, 1fr),
    inset: 10pt,
    align: horizon,
    fill: (_, row) => if calc.odd(row) { luma(240) } else { white },
    [*Source*], [*Description*], [*Format*],
    [Contents], [Catalog of movies and series], [CSV],
    [Users], [Registered users data], [CSV],
    [Viewing Logs], [User activity logs (High Volume)], [JSON],
    [Social Media], [Mentions and interactions], [JSON]
  )

  #v(1em)
  #stress("Faker Data Builder"): Simulates realistic production data with referential integrity and temporal consistency.
]

// --- Section 2: Architecture & Infrastructure (Nathan) ---

#title-slide[
  Architecture & Infrastructure
]

// Slide 4: Global Architecture
#slide(title: "Global Architecture (ELT)")[
  
  // A Typst-native flow diagram
  #align(center)[
    #grid(
      columns: (auto, auto, auto, auto, auto, auto, auto),
      gutter: 0.5em,
      align: horizon,
      rect(fill: luma(230), inset: 8pt, radius: 4pt)[*Generation* \ Python (Faker)],
      text(size: 20pt)[$->$],
      rect(fill: rgb("#e8f0fe"), inset: 8pt, radius: 4pt)[*Data Lake* \ GCS (Raw)],
      text(size: 20pt)[$->$],
      rect(fill: rgb("#cce5ff"), inset: 8pt, radius: 4pt)[*Warehouse* \ BigQuery (Ext Tables)],
      text(size: 20pt)[$->$],
      rect(fill: rgb("#fff2cc"), inset: 8pt, radius: 4pt)[*Consumption* \ PowerBI]
    )
  ]
  
  #v(1em)
  
  #cols(columns: (1fr, 1fr), gutter: 1em)[
    *The Philosophy*
    - *Modern ELT:* Load raw data first, transform in-warehouse.
    - *Orchestrator:* #stress("Prefect") manages dependencies.
    - *Platform:* 100% Serverless on GCP.
  ][
    *Key Components*
    - #stress("Faker"): Simulates production inputs.
    - #stress("dbt"): Medallion architecture transformations.
    - #stress("Terraform"): Fully reproducible Infra.
  ]
]

// Slide 5: Development Workflow & Infrastructure
#slide(title: "Development Workflow & Infrastructure")[
  
  #grid(
    columns: (1fr, 1fr),
    gutter: 2em,
    
    // Left Column: DevEx & CI/CD
    stack(dir: ttb, spacing: 1em,
      rect(fill: luma(245), inset: 10pt, radius: 5pt, width: 100%)[
        *1. Developer Experience (Mise)*
        - *Tooling:* Manages versions for Terraform, Python, and dbt via `mise.toml`.
        - *Templating:* Ensures consistent environment setup across the team.
        - *No "Works on my machine":* Unified config.
      ],
      rect(fill: luma(235), inset: 10pt, radius: 5pt, width: 100%)[
        *2. Version Control (Git & GitHub)*
        - *Tracking:* Full history of code changes.
        - *CI/CD:* GitHub Actions triggers on Pull Requests.
          - Linting (SQLFluff, Black).
          - `dbt compile` checks.
      ]
    ),

    // Right Column: Infrastructure as Code
    rect(fill: rgb("#e8f0fe"), inset: 1em, radius: 8pt, width: 100%, height: 100%)[
      *3. Infrastructure (Terraform)*
      
      #v(0.5em)
      *Provisioning on GCP:*
      - *State:* Remote state in GCS (Collaboration).
      - *Security:* IAM Roles defined in code.
      - *Environments:*
        - `dev`: Sandbox for testing.
        - `prod`: Live data pipeline.
      
      #v(1em)
      #align(center)[
        #text(size: 0.8em, style: "italic")[
          Infrastructure is treated exactly like software.
        ]
      ]
    ]
  )
]

// --- Section 3: Ingestion & Transformation (Cyprien) ---

#title-slide[
  Ingestion & Transformation
]

// Slide 6: Ingestion Workflow
#slide(title: "Ingestion: Generation & Storage")[
  *Prefect Flow:* `refill_bucket_flow`
  
  #cols(columns: (1fr, 1fr), gutter: 2em)[
    #rect(fill: rgb("#e6fffa"), inset: 10pt, radius: 5pt, width: 100%)[
      *1. Generator (`seed_script.py`)*
      - `contents.csv` (Catalog)
      - `users.csv` (User Base)
      - `viewing_logs.json` (High Vol.)
      - `mentions.json` (Unstructured)
    ]
  ][
    #rect(fill: rgb("#e6f7ff"), inset: 10pt, radius: 5pt, width: 100%)[
      *2. Data Lake (GCS)*
      - Bucket: `raw_data/ingested-data`
      - *Partitioning:* By Date/Run
      - *Safety:* Idempotent execution
    ]
  ]

  #v(1em)
  *Key Technical Choice:* 
  Simulating a live production environment rather than static file uploads.
]

// Slide 7: Transformation Layer
#slide(title: "Transformation Strategy (dbt)")[
  *The "Medallion" Architecture in BigQuery*

  #grid(
    columns: (1fr, auto, 1fr, auto, 1fr),
    gutter: 0.5em,
    align: horizon,
    
    // Bronze
    rect(fill: rgb("#cd7f32"), inset: 10pt, radius: 5pt, width: 100%)[
      #align(center)[*Bronze* \ (Raw)]
      #text(size: 0.6em)[External Tables (No Load Cost)]
    ],
    $->$,
    // Silver
    rect(fill: rgb("#c0c0c0"), inset: 10pt, radius: 5pt, width: 100%)[
      #align(center)[*Silver* \ (Staging/Int)]
      #text(size: 0.6em)[Cleaning & Deduplication]
    ],
    $->$,
    // Gold
    rect(fill: rgb("#ffd700"), inset: 10pt, radius: 5pt, width: 100%)[
      #align(center)[*Gold* \ (Marts)]
      #text(size: 0.6em)[Star Schema (Facts/Dims)]
    ]
  )

  #v(1em)
  
  #cols(columns: (1fr, 1fr), gutter: 1em)[
    *Layer Details*
    - *Staging:* 1:1 Views, Renaming.
    - *Intermediate:* Complex joins (e.g., `int__viewing_enriched`).
    - *Marts:* Final Business Logic.
  ][
    *Why External Tables?*
    We query GCS directly using `create_external_sources`. 
    - No data duplication.
    - Lower storage costs.
  ]
]
// --- Section 3: Ingestion & Transformation Layers (8:00 - 13:00) ---

#title-slide[
  Ingestion & Transformation
]

// Slide 6: Workflow #2 - Ingestion & Data Lake
#slide(title: "Ingestion & Data Lake")[
  *Workflow: Faker -> GCS*
  
  #cols(columns: (1fr, 1fr), gutter: 2em)[
    - *Generation:* `seed_script.py` creates synthetic data.
    - *Storage:* Uploaded to GCS `raw_data/` bucket.
    - *Partitioning:* Organized by execution timestamp.
    - *Idempotency:* Prevents data duplication on re-runs.
  ][
    // Placeholder for Ingestion diagram
    #rect(width: 100%, height: 60%, fill: luma(240), radius: 10pt)[
      #align(center + horizon)[*Ingestion Flow Diagram*]
    ]
  ]
]

// Slide 7: Workflow #3 - Transformation Layer
#slide(title: "Transformation Layer (dbt)")[
  *Medallion Architecture*
  
  #align(center)[
    // Placeholder for Medallion Architecture diagram
    #rect(width: 90%, height: 40%, fill: luma(240), radius: 10pt)[
      #align(center + horizon)[
        *Bronze (Raw)* -> *Silver (Staging/Int)* -> *Gold (Marts)*
      ]
    ]
  ]
  
  #v(1em)
  #cols(columns: (1fr, 1fr, 1fr), gutter: 1em)[
    #framed(title: "Bronze")[Raw ingestion via External Tables]
  ][
    #framed(title: "Silver")[Cleaning, deduplication, enrichment @dbt]
  ][
    #framed(title: "Gold")[Star Schema (Facts & Dimensions) for BI]
  ]
]

// --- Section 4: Analytics & Visualization (13:00 - 20:00) ---

#title-slide[
  Analytics & Visualization
]

// Slide 8: Final Data Model
#slide(title: "Final Data Model")[
  *Star Schema for Reporting*
  
  #cols(columns: (1fr, 1fr), gutter: 1em)[
    - *Fact Table:*
      - `fct__viewings`
    - *Dimension Tables:*
      - `dim__users`
      - `dim__content`
      - `dim__devices`
      - `dim__date`
  ][
    // Placeholder for ERD
    #rect(width: 90%, height: 80%, fill: luma(240), radius: 10pt)[
      #align(center + horizon)[*Entity Relationship Diagram (ERD)*]
    ]
  ]
]

// Slide 9: PowerBI Dashboard
#slide(title: "PowerBI Dashboard")[
  *Visualizing the Insights*
  
  #align(center)[
    // Placeholder for Dashboard screenshot
    #rect(width: 90%, height: 65%, fill: luma(240), radius: 10pt)[
      #align(center + horizon)[*PowerBI Dashboard Screenshot*]
    ]
  ]
  
  - *Key KPIs:* Total views, active users, content performance.
  - *Interactivity:* Filters by date, device, and content type.
  - *DirectQuery:* Connected directly to BigQuery Gold layer @powerbi.
]

// Slide 10: Conclusion & Q&A
#focus-slide[
  *Thank You!*
  
  Questions?
  
  #v(2em)
  #text(size: 0.5em)[
    Built with: Prefect, GCP, dbt, PowerBI
  ]
]

// Bibliography Slide
#let bib = bibliography("references.yml")
#bibliography-slide(bib)
